# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 10:55
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20170109_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='page',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Les tags doivent être séparés par une virgule', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
    ]
